---
# handlers file for gofile role

- name: reread and update
  ansible.builtin.shell: supervisorctl reread && supervisorctl update
  become: true

- name: restart all instances
  ansible.builtin.shell: >
    supervisorctl restart gofile-{{ item.port }}
  loop: "{{ gofile_list }}"
  become: true
